@startuml

file "Application Configuration" as a
file "Components" as c
file "Scopes" as s
file "Workload Definitions" as wd
file "Trait Definitions" as td
file "Scope Definitions" as sd

c -d-> wd: references
s -d-> sd: references

a -d-> c: references
a -d-> td: references
a -d-> s: references

wd -[hidden]r-> td
td -[hidden]r-> sd

@enduml