# Verrazzano Language Configuration
# All nl configurations are set here.

[en]
  title = "Verrazzano Enterprise Container Platform"
  description = "A hybrid multi-cloud Kubernetes based Enterprise Container Platform for running both cloud-native and traditional applications"
  languageName ="English"
  contentDir = "content/en"
  # Weight used for sorting.
  weight = 1
