defaultMarkdownHandler = "goldmark"

[goldmark]
  [goldmark.renderer]
    unsafe = true

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

# Configuration for the Chroma syntax highlighting
# https://gohugo.io/getting-started/configuration-markup/#highlight
[highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "tango"
  tabWidth = 4

# Specify which level of headings to show in the right-side TOC
[tableOfContents]
  endLevel = 3
  startLevel = 1
