# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "bbef87cd33f0884bd"

[[versions]]
version = "latest"
url = "https://docs.oracle.com/en/cloud/iaas/verrazzano/vzdoc/latest/docs/"

[[versions]]
version = "v0.17"
url = "https://docs.oracle.com/en/cloud/iaas/verrazzano/vzdoc/v0.17/docs/"
