# Verrazzano "production" site configuration (adds to or overides "_default")
ignoreFiles = ['content/en/docs/setup/private-registry/private-registry-full-distribution\.md$']

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-177109661-1"
